#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export PATH=$PATH:/util_modules

SRC_DIR=$1
echo "SRC_DIR:             $SRC_DIR" 1>&2
echo "BUILD_ID:	           $BUILD_ID" 1>&2
echo "BUILD_NAME:          $BUILD_NAME" 1>&2
echo "BUILD_JOB_NAME:      $BUILD_JOB_NAME" 1>&2
echo "BUILD_PIPELINE_NAME: $BUILD_PIPELINE_NAME" 1>&2
echo "BUILD_TEAM_NAME:     $BUILD_TEAM_NAME" 1>&2
echo "ATC_EXTERNAL_URL:    $ATC_EXTERNAL_URL" 1>&2

payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX) # STDIN params
cat > $payload <&0
git_url=$(jq -r '.params.git_url // ""' < $payload)

echo "input fields: $(jq -r '.'< $payload)" 1>&2
echo "git_url: $git_url"

if [ -n "$git_url" ]
then
    source $(dirname $0)/common.sh
    load_pubkey $payload
    qiniu_accesskey=$(jq -r '.source.qiniu_accesskey // ""' < $payload)
    qiniu_secretkey=$(jq -r '.source.qiniu_secretkey // ""' < $payload)
    qiniu_accountname=$(jq -r '.source.qiniu_accountname // ""' < $payload)

    mkdir -p $SRC_DIR/git_source
    echo "git clone --single-branch --depth=1 $git_url --branch master $SRC_DIR/git_source"
    git clone --single-branch --depth=1 $git_url --branch master $SRC_DIR/git_source

    cd $SRC_DIR
    cp $SRC_DIR/git_source/qiniu_cmds qiniu_cmds
    chmod 777 qiniu_cmds

    echo "+ qshell account ${qiniu_accesskey} ${qiniu_secretkey} ${qiniu_accountname}"
    eval "qshell account ${qiniu_accesskey} ${qiniu_secretkey} ${qiniu_accountname}"
    echo "+ ./qiniu_cmds"
    ./qiniu_cmds

    rm -rf $SRC_DIR/git_source
    rm -rf qiniu_cmds
else
    echo "git_url is null"
fi

jq -n "{
  version: {
    BUILD_NAME: \"$BUILD_NAME\"
  }
}" >&3
