#!/usr/bin/env bash

set -e

SRC_DIR=$1
cd $SRC_DIR
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export PATH=$PATH:/util_modules

echo "SRC_DIR:             $SRC_DIR"
echo "BUILD_ID:	           $BUILD_ID"
echo "BUILD_NAME:          $BUILD_NAME"
echo "BUILD_JOB_NAME:      $BUILD_JOB_NAME"
echo "BUILD_PIPELINE_NAME: $BUILD_PIPELINE_NAME"
echo "BUILD_TEAM_NAME:     $BUILD_TEAM_NAME"
echo "ATC_EXTERNAL_URL:    $ATC_EXTERNAL_URL"

SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

qiniu_accesskey=$(jq -r '.source.qiniu_accesskey // ""' < $SCRIPT_INPUT)
qiniu_secretkey=$(jq -r '.source.qiniu_secretkey // ""' < $SCRIPT_INPUT)
qiniu_accountname=$(jq -r '.source.qiniu_accountname // ""' < $SCRIPT_INPUT)
CMDS=$(jq -r '.params.cmds + [.params.cmd]|join(",")'< $SCRIPT_INPUT)

echo "input fields: $(jq -r '.'< $SCRIPT_INPUT)"
echo "cmds:   $CMDS"

if [ -n "$CMDS" ]
then
    echo "+ qshell account ${qiniu_accesskey} ${qiniu_secretkey} ${qiniu_accountname}"
    eval "qshell account ${qiniu_accesskey} ${qiniu_secretkey} ${qiniu_accountname}"
	IFS=,;
	for CMD in $CMDS;
	do
        echo "+ $CMD";
        eval $CMD;
	done;
else
    echo "CMDS are empty"
fi

jq -n "{
  version: {
    CMDS: \"$CMDS\"
  }
}" >&3
